package com.wenox.processing.domain;

public enum OutcomeStatus {
  GENERATION_STARTED,
  MIRROR_READY,
  MIRROR_FAILURE,
  SCRIPT_CREATION_SUCCESS,
  SCRIPT_CREATION_FAILURE,
  SCRIPT_FAILURE,
  OUTCOME_READY
}
