package com.wenox.anonymisation.domain;

public enum AnonymisationOperation {
  COLUMN_SHUFFLE,
  GENERALISATION,
  HASHING,
  PATTERN_MASKING,
  PERTURBATION,
  RANDOM_NUMBER,
  ROW_SHUFFLE,
  SHORTENING,
  SUBSTITUTION,
  SUPPRESSION,
  TOKENIZATION
}
