export const FILE_UPLOADER_TIMEOUT = 500;
export const SKELETON_TIMEOUT = 600;
export const TEMPLATE_GENERATION_STEP_TIMEOUT = 1000;
export const SHOW_TEMPLATE_GENERATION_STEPS_TIMEOUT = 1000;
export const SHOW_WORKSHEET_SUMMARY_TIMEOUT = 600;
