# Miscellaneous
server.environment.cloud: true

# Uploading module configuration
uploading.templates.path: /var/lib/anonymisation/templates

# Processing module configuration
processing:
  anonymisations:
    scripts.path: /var/lib/anonymisation_platform/anonymisations/scripts
  dumps:
    scripts.path: /var/lib/anonymisation_platform/dumps/scripts
    archives.path: /var/lib/anonymisation_platform/dumps/archives
